### ISSUE TITLE
NoMethodError: undefined method `slice!' for nil:NilClass

### ISSUE THREAD

**Issue by gf3** [celluloid/celluloid-redis#4] opened 2013-03-26 20:33 UTC
Seeing this come up occasionally in my logs.

I've [gist'd](https://gist.github.com/gf3/3140906e7dfa23e8904e) the full stack trace and the method from closest ancestor of my code. It looks like Celluloid might need to do a `nil` check [in Redis::Connection::Celluloid#read](https://github.com/celluloid/celluloid-redis/blob/master/lib/redis/connection/celluloid.rb#L54)—I'm not entirely familiar with what's expected from redis, though.

**Comment by tarcieri** [comment] 2013-03-28 22:13
Seems kind of odd: the core Ruby `TCPSocket#gets` method seems to have the same semantics as far as returning nil on close.

Perhaps I should look elsewhere in the Redis driver for how this is handled

**Comment by simonrobson** [comment] 2013-03-31 09:43
Looks like the redis-rb ruby driver actually swaps in its own implementation of gets in `Redis::Connection::SocketMixin`. As far as I can see it changes the semantics of`TCPSocket#gets` to never return nil, instead raising `Errno::ECONNRESET` on end of file.

I recall seeing errors like that @gf3 describes when running the redis-rb test suite on jruby against my own attempt a celluloid driver recently. Will try to reproduce and get a patch in.

**Comment by tarcieri** [comment] 2013-04-01 16:42
@gf3 can you confirm this is fixed by #5? If so I can spin a new gem

**Comment by gf3** [comment] 2013-04-02 16:51
Sure, I can give it a shot. Might take some time to show up in the logs as I'm not sure what triggered it.

**Comment by gf3** [comment] 2013-04-05 22:48
It _seems_ to be resolved. I haven't seen the error in a few days.

**Comment by tarcieri** [comment] 2013-04-07 18:24
Cool, will spin a new gem.

**Comment by tarcieri** [comment] 2013-04-07 21:59
This should be fixed in 0.0.2.

**Closed as completed by tarcieri** 2013-04-07 21:59 UTC
